USE [Teste]
GO
IF OBJECT_ID('dbo.P_NOTA_FISCAL_VALOR_IMPOSTO') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_NOTA_FISCAL_VALOR_IMPOSTO
    IF OBJECT_ID('dbo.P_NOTA_FISCAL_VALOR_IMPOSTO') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_NOTA_FISCAL_VALOR_IMPOSTO >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_VALOR_IMPOSTO APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE P_NOTA_FISCAL_VALOR_IMPOSTO
AS
BEGIN

  SELECT [cfop] as CDOP
        ,SUM(ISNULL([BaseIcms],0)) AS [Valor Total da Base de ICMS]
        ,SUM(ISNULL([ValorIcms],0)) AS [Valor Total do ICMS]
        ,SUM(ISNULL([BaseIpi],0)) AS [Valor Total da Base de IPI]
        ,SUM(ISNULL([ValorIpi],0)) AS [Valor Total do IPI]
  FROM [dbo].[NotaFiscalItem]
  GROUP BY [Cfop]

END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_VALOR_IMPOSTO TO [public]
go
IF OBJECT_ID('dbo.P_NOTA_FISCAL_VALOR_IMPOSTO') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_VALOR_IMPOSTO CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_NOTA_FISCAL_VALOR_IMPOSTO >>>'
go